/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class Library {
  public static void main(String[] args) {
LinkedList<Integer> n = new LinkedList<>();
    n.add(5);
    n.add(6);
    n.add(7);

    System.out.println(n.toString());
    System.out.println(n.include(7));



  }
}
