/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class Library {
  public static void main(String[] args) {
LinkedList<Integer> n = new LinkedList<>();
    n.add(5);
    n.add(6);
    n.add(7);

    System.out.println(n.toString());
    System.out.println(n.include(7));
//    n.addAfter(6,6);
//    n.addBefore(7,6);
//    n.Append(1);

    System.out.println(n.toString());
//    int c =n.kthFromEnd(6);
//
//    System.out.println(n.kthFromEnd(7));
//add
    System.out.println(n.kthFromEnd(3));




  }
}
