/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quick.sort;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      int [] arr = {2,3,5,7,13,11};
      int n = arr.length;
      System.out.println(Arrays.toString(QuickSort.quickSort( arr,0,n-1)));
    }
}
