/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.repeated.word;

public class App {


    public static void main(String[] args) {

      System.out.println(HashmapRepeatedWord.repeatedWord("Once upon A time, there was a brave princess who..."));
    }
}
