/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import java.util.ArrayList;
import java.util.LinkedList;

public class App {

    public static void main(String[] args) {
//HashTable hashTable = new HashTable();
//hashTable.add("mansoor",7);
//      System.out.println(hashTable.get("mansoor"));
//      hashTable.add("mansoor",5);
//      System.out.println(hashTable.get("mansoor"));
//      hashTable.add("mayada","aa");
//
//      System.out.println( hashTable.get("mayada"));
//
//      for(LinkedList n :  hashTable.getBucket()){
//        System.out.print(n + ", ");
//        if(n != null){
//          System.out.println(n.size());
//        }
//      }
//      HashTable h = new HashTable();
//      System.out.println(
//        "\n"+ h.hash("ASAC")
//      );
      HashTable<String> Hash1 = new HashTable<>();
      HashTable<String> Hash2 = new HashTable<>();
      Hash1.add("fond", "enamored");
      Hash1.add("wrath", "anger");
      Hash1.add("diligent", "employed");
      Hash1.add("outfit", "garb");
      Hash1.add("guide", "usher");

      Hash2.add("fond", "averse");
      Hash2.add("wrath", "delight");
      Hash2.add("diligent", "idle");
      Hash2.add("guide", "follow");
      Hash2.add("flow", "jam");
      ArrayList<ArrayList<String>> list =Hash1.leftJoin(Hash1,Hash2);
      System.out.println(list);
    }
}
