/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import java.util.LinkedList;

public class App {

    public static void main(String[] args) {
HashTable hashTable = new HashTable();
hashTable.add("mansoor",7);
      System.out.println(hashTable.get("mansoor"));
      hashTable.add("mansoor",5);
      System.out.println(hashTable.get("mansoor"));
      hashTable.add("mayada","aa");

      System.out.println( hashTable.get("mayada"));

      for(LinkedList n :  hashTable.getBucket()){
        System.out.print(n + ", ");
        if(n != null){
          System.out.println(n.size());
        }
      }
      HashTable h = new HashTable();
      System.out.println(
        "\n"+ h.hash("ASAC")
      );
    }
}
