/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge.sort;

public class App {


    public static void main(String[] args) {
      int[] arr = {2,3,5,7,13,11};
      for (int i: MergeSort.mergesort(arr)) {
        System.out.println(i);
      }

    }
}
